gantt
        dateFormat  YYYY-MM-DD
        title Course of Proposed Work
        section Learning tasks
        Study Category Theory             :active, 2017-01-24, 90d
        Study Functional Programming      :active, 2017-02-12, 90d
        Study FRP                         :active, 2017-03-09, 90d

        section Design/Construction
        Design of FRP framework           :crit, active, 2017-04-01, 12w
        virtualME Adaptation              :crit, active, 2017-06-01, 6w
        Control Theory Applications       :crit, active, 2017-07-07, 6w

        section Authorship
        Thesis writing                    :crit, active, 2017-06-01, 17w

        section PhD Deadlines
        Deadline                          :crit, 2017-06-12, 1d
        Deadline                          :crit, 2017-10-10, 1d
